# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 0. Host docker configuration
host: 0.0.0.0
port: 4000

# 1. Files excluded from Jekyll builds
exclude:
- docker
- vendor
- docker-compose.yml
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- elements.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: GabrielSoaresOn # jekyll-seo-tag > Owners twitter username
author: Gabriel Felipe Soares # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Gabriel Felipe Soares # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/GabrielSoaresOn
    - https://www.facebook.com/gabriel.f.soares.7
    - https://www.linkedin.com/in/gabrielfelipesoares
    - https://github.com/gabrielfs7
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Gabriel's Blog" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Sharing my thoughts about IT related subjects" # Site description and default description, also used in jekyll-seo-tag
url: "https://gabrielfs7.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/gabrielfs7/gabrielfs7.github.io"
email: "gabrielfs7@gmail.com"
# disqus: "gabrielfs7.github.io-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Created by Gabriel Felipe Soares
  url: https://gabrielfs7.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/GabrielSoaresOn
  LinkedIn: https://www.linkedin.com/in/gabrielfelipesoares
  GitHub: https://github.com/gabrielfs7
  link: https://gabrielfs7.github.io
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
